name: Docker Image CI
#name: Publish Docker image
#on:
#  release:
#    types: [published]
on: [push, pull_request]

jobs:
  buildx:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - uses: docker/login-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2.2.2
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          context: .
          file: ./plugin-init/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/chlunde/humio-jaeger-storage:latest
            ghcr.io/chlunde/humio-jaeger-storage:${{ github.sha }}
