on:
  push:
    branches: [master]
  pull_request:
name: Test and push image
jobs:
  test:
    name: Build and run go test
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest] #, macos-latest, windows-latest]

    services:
      humio:
        image: docker.io/humio/humio
        ports:
          - 8080:8080
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
  buildx:
    needs: [test]
    name: Build Docker image - when on master - push to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - uses: docker/login-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2.4.0
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          context: .
          file: ./plugin-init/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/chlunde/humio-jaeger-storage:latest
            ghcr.io/chlunde/humio-jaeger-storage:${{ github.sha }}
